#!/usr/bin/env python3
"""Build the TOP service section and static service pages from data/services.json.

Usage: python3 tools/build-services.py [--check]
The same command runs in the Pages workflow, so a service addition needs data only.
"""

from __future__ import annotations

import argparse
import html
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "data"
TEMPLATES = ROOT / "tools" / "templates"
SERVICES_DIR = ROOT / "services"
SITE = "https://contentsx.jp"
SIGNATURE = "<!-- Generated by tools/build-services.py; edit data/services.json -->"
SLUG = re.compile(r"^[a-z0-9-]+$")
PLACEHOLDER = re.compile(r"{{[A-Z_]+}}")


def esc(value: object) -> str:
    return html.escape(str(value), quote=True)


def read_json(path: Path):
    return json.loads(path.read_text(encoding="utf-8"))


def validate(services: list[dict], groups: list[dict]) -> None:
    if not isinstance(services, list) or not isinstance(groups, list):
        raise ValueError("services and groups must be arrays")
    required = {"id", "slug", "group", "name", "eyebrow", "shortCopy", "hoverSummary", "tags", "icon", "href", "featured"}
    group_ids: set[str] = set()
    for group in groups:
        if not isinstance(group, dict) or not all(group.get(key) for key in ("id", "name", "tagline", "summary")):
            raise ValueError(f"invalid group: {group!r}")
        if not SLUG.fullmatch(group["id"]) or group["id"] in group_ids:
            raise ValueError(f"invalid or duplicate group: {group['id']!r}")
        group_ids.add(group["id"])
    ids: set[str] = set()
    slugs: set[str] = set()
    for service in services:
        if not isinstance(service, dict) or not required.issubset(service):
            raise ValueError(f"service missing required fields: {service!r}")
        service_id, slug = service["id"], service["slug"]
        if not SLUG.fullmatch(service_id) or service_id in ids:
            raise ValueError(f"invalid or duplicate service id: {service_id!r}")
        if not SLUG.fullmatch(slug) or slug in slugs:
            raise ValueError(f"invalid or duplicate slug: {slug!r}")
        if service["group"] not in group_ids:
            raise ValueError(f"unknown group for {service_id}: {service['group']!r}")
        if service["href"] != f"/services/{slug}/":
            raise ValueError(f"href must match slug for {service_id}")
        if not (ROOT / "material" / "web-system" / "icons" / f"{service['icon']}.svg").is_file():
            raise ValueError(f"unknown icon for {service_id}: {service['icon']!r}")
        if not all(isinstance(service[key], str) and service[key].strip() for key in ("name", "eyebrow", "shortCopy", "hoverSummary")):
            raise ValueError(f"empty text field for {service_id}")
        if not isinstance(service["tags"], list) or not all(isinstance(tag, str) and tag for tag in service["tags"]):
            raise ValueError(f"invalid tags for {service_id}")
        if not isinstance(service["featured"], bool):
            raise ValueError(f"invalid featured for {service_id}")
        for field in ("features", "challenges", "steps", "useCases"):
            if field in service and (not isinstance(service[field], list) or not all(isinstance(item, str) and item for item in service[field])):
                raise ValueError(f"invalid {field} for {service_id}")
        for faq in service.get("faqs", []):
            if not isinstance(faq, dict) or not faq.get("question") or not faq.get("answer"):
                raise ValueError(f"invalid FAQ for {service_id}")
        if "image" in service:
            image = service["image"]
            if not isinstance(image, str) or not image.startswith("/material/"):
                raise ValueError(f"invalid image for {service_id}")
            image_path = (ROOT / image.lstrip("/")).resolve()
            if not image_path.is_relative_to(ROOT / "material") or not image_path.is_file():
                raise ValueError(f"missing or unsafe image for {service_id}")
        ids.add(service_id)
        slugs.add(slug)


def render_template(name: str, values: dict[str, str]) -> str:
    result = (TEMPLATES / name).read_text(encoding="utf-8")
    for key, value in values.items():
        result = result.replace("{{" + key + "}}", value)
    remaining = PLACEHOLDER.findall(result)
    if remaining:
        raise ValueError(f"unfilled template values: {remaining}")
    return result


def render_icon(name: str, class_name: str = "cxs-icon") -> str:
    source = (ROOT / "material" / "web-system" / "icons" / f"{name}.svg").read_text(encoding="utf-8").strip()
    return source.replace("<svg ", f'<svg class="{class_name}" aria-hidden="true" focusable="false" ', 1)


def render_tags(tags: list[str], class_name: str = "cxs-tags") -> str:
    if not tags:
        return ""
    return f'<ul class="{class_name}">' + "".join(f"<li>{esc(tag)}</li>" for tag in tags) + "</ul>"


def render_card(service: dict, context: str) -> str:
    control_id = f"cxs-{context}-{service['slug']}-more"
    name = esc(service["name"])
    href = esc(service["href"])
    return f'''<article class="cxs-card" data-group="{esc(service['group'])}" data-featured="{str(service['featured']).lower()}">
  <div class="cxs-card__intro">
    <div class="cxs-card__icon">{render_icon(service['icon'])}</div>
    <h3>{name}</h3>
    <p class="cxs-card__short">{esc(service['shortCopy'])}</p>
    <div class="cxs-card__actions">
      <button class="cxs-card__expand" type="button" aria-expanded="false" aria-controls="{control_id}">概要を見る</button>
      <a class="cxs-icon-button" href="{href}" aria-label="{name}の詳細を見る">{render_icon('arrow-right')}</a>
    </div>
  </div>
  <div class="cxs-card__more" id="{control_id}">
    <button class="cxs-card__close" type="button" aria-label="{name}の概要を閉じる">閉じる ×</button>
    <h4>{name}</h4>
    <p>{esc(service['hoverSummary'])}</p>
    {render_tags(service['tags'], 'cxs-tags cxs-tags--on-accent')}
    <a class="cxs-card__detail-link" href="{href}">詳しく見る <span aria-hidden="true">→</span></a>
  </div>
</article>'''


def render_group(group: dict, services: list[dict], context: str) -> str:
    members = [service for service in services if service["group"] == group["id"]]
    if not members:
        return ""
    group_id = esc(group["id"])
    heading_id = f"cxs-{context}-{group_id}-title"
    cards = "\n".join(render_card(service, context) for service in members)
    return f'''<section class="cxs-section cxs-service-group" id="{context}-group-{group_id}" data-group="{group_id}" aria-labelledby="{heading_id}">
  <div class="cxs-container">
    <div class="cxs-section-header">
      <div><p class="cxs-eyebrow">{esc(group.get('eyebrow', group['name']))}</p><h2 id="{heading_id}">{esc(group['name'])}</h2><p class="cxs-section-header__tagline">{esc(group['tagline'])}</p></div>
      <p class="cxs-section-header__summary">{esc(group['summary'])}</p>
    </div>
    <div class="cxs-service-grid">{cards}</div>
  </div>
</section>'''


def render_home(services: list[dict], groups: list[dict]) -> str:
    sections = "\n".join(render_group(group, services, "home") for group in groups)
    return f'''<div class="cxs-home-services" id="services" aria-label="サービス紹介">
  <div class="cxs-container cxs-home-services__intro"><div><p class="cxs-eyebrow">OUR SERVICES</p><h2>売上につながる、サービス。</h2></div><a class="cxs-text-link" href="/services/">サービス一覧を見る <span aria-hidden="true">→</span></a></div>
  {sections}
</div>'''


def render_list(services: list[dict], groups: list[dict]) -> str:
    sections = "\n".join(render_group(group, services, "list") for group in groups)
    return render_template("service-list.html.tpl", {"GROUPS": sections})


def render_list_items(items: list[str], class_name: str = "cxs-feature-list") -> str:
    return f'<ul class="{class_name}">' + "".join(f"<li>{esc(item)}</li>" for item in items) + "</ul>"


def render_detail_sections(service: dict, services: list[dict]) -> str:
    slug = service["slug"]
    tabs: list[tuple[str, str]] = [("overview", "概要")]
    overview = f'<p class="cxs-detail-lead">{esc(service["hoverSummary"])}</p>'
    if service.get("challenges"):
        overview += '<h3>こんな課題に</h3>' + render_list_items(service["challenges"])
    panels = [("overview", overview)]
    if service.get("features"):
        tabs.append(("features", "できること"))
        panels.append(("features", "<h3>サービスでできること</h3>" + render_list_items(service["features"])))
    related = [item for item in services if item["group"] == service["group"] and item["id"] != service["id"]]
    if related:
        tabs.append(("related", "関連サービス"))
        links = "".join(f'<li><a href="{esc(item["href"])}">{esc(item["name"])} <span aria-hidden="true">→</span></a></li>' for item in related)
        panels.append(("related", f'<h3>同じカテゴリのサービス</h3><ul class="cxs-related-list">{links}</ul>'))
    buttons = "".join(
        f'<button type="button" role="tab" id="cxs-tab-{slug}-{key}" aria-controls="cxs-panel-{slug}-{key}" aria-selected="{str(index == 0).lower()}" tabindex="{0 if index == 0 else -1}">{label}</button>'
        for index, (key, label) in enumerate(tabs)
    )
    contents = "".join(
        f'<section class="cxs-tab-panel" role="tabpanel" id="cxs-panel-{slug}-{key}" aria-labelledby="cxs-tab-{slug}-{key}" tabindex="0">{body}</section>'
        for key, body in panels
    )
    result = f'''<section class="cxs-section cxs-detail-content" aria-label="{esc(service['name'])}の詳細">
  <div class="cxs-container"><h2 class="sr-only">{esc(service['name'])}の詳細</h2><div class="cxs-tabs" role="tablist" aria-label="サービス情報">{buttons}</div><div class="cxs-tab-panels">{contents}</div></div>
</section>'''
    for field, label in (("steps", "導入の流れ"), ("useCases", "活用シーン")):
        if service.get(field):
            result += f'<section class="cxs-section cxs-detail-extra"><div class="cxs-container"><h2>{label}</h2>{render_list_items(service[field])}</div></section>'
    if service.get("faqs"):
        faq_items = "".join(
            f'<details class="cxs-accordion"><summary>{esc(faq["question"])}</summary><p>{esc(faq["answer"])}</p></details>'
            for faq in service["faqs"]
        )
        result += f'<section class="cxs-section cxs-detail-extra"><div class="cxs-container"><h2>よくある質問</h2>{faq_items}</div></section>'
    return result


def render_detail(service: dict, services: list[dict]) -> str:
    visual = (f'<img src="{esc(service["image"])}" alt="{esc(service["name"])}のサービスイメージ" loading="lazy">'
              if service.get("image") else render_icon(service["icon"], "cxs-detail-hero__visual-icon"))
    values = {
        "GROUP_ID": esc(service["group"]),
        "NAME": esc(service["name"]),
        "EYEBROW": esc(service["eyebrow"]),
        "SHORT_COPY": esc(service["shortCopy"]),
        "SUMMARY": esc(service["hoverSummary"]),
        "TAGS": render_tags(service["tags"]),
        "ICON": render_icon(service["icon"]),
        "VISUAL_ICON": visual,
        "DETAIL_SECTIONS": render_detail_sections(service, services),
    }
    return render_template("service-detail.html.tpl", values)


def script_json(data: dict) -> str:
    payload = json.dumps(data, ensure_ascii=False, separators=(",", ":")).replace("<", "\\u003c")
    return f'<script type="application/ld+json">{payload}</script>'


def breadcrumbs_json(items: list[tuple[str, str]]) -> dict:
    return {"@context": "https://schema.org", "@type": "BreadcrumbList", "itemListElement": [
        {"@type": "ListItem", "position": index, "name": name, "item": url}
        for index, (name, url) in enumerate(items, 1)
    ]}


def extract_block(source: str, tag: str) -> str:
    opening = re.search(rf"<{tag}\b[^>]*>", source)
    if not opening:
        raise ValueError(f"missing <{tag}> in index.html")
    closing = source.find(f"</{tag}>", opening.end())
    if closing < 0:
        raise ValueError(f"missing </{tag}> in index.html")
    return source[opening.start(): closing + len(tag) + 3]


def render_page(body: str, title: str, description: str, path: str, json_ld: list[dict], header: str, footer: str) -> str:
    canonical = f"{SITE}{path}"
    page = render_template("service-page.html.tpl", {
        "TITLE": esc(title), "DESCRIPTION": esc(description), "CANONICAL": esc(canonical),
        "JSON_LD": "\n  ".join(script_json(item) for item in json_ld),
        "HEADER": header, "FOOTER": footer, "BODY": body,
    })
    return page.replace("<!DOCTYPE html>", f"<!DOCTYPE html>\n{SIGNATURE}", 1)


def render_tokens(tokens: dict) -> str:
    mapping = {
        "ink": tokens["colors"]["ink"], "text": tokens["colors"]["text"],
        "muted": tokens["colors"]["muted"], "border": tokens["colors"]["border"],
        "background": tokens["colors"]["background"], "surface": tokens["colors"]["surface"],
        "sales": tokens["colors"]["sales"], "sales-soft": tokens["colors"]["salesSoft"],
        "creative": tokens["colors"]["creative"], "creative-soft": tokens["colors"]["creativeSoft"],
        "container-max": tokens["layout"]["containerMax"],
        "gutter-desktop": tokens["layout"]["pageGutterDesktop"],
        "gutter-mobile": tokens["layout"]["pageGutterMobile"],
        "section-desktop": tokens["layout"]["sectionSpaceDesktop"],
        "section-mobile": tokens["layout"]["sectionSpaceMobile"],
        "radius-sm": tokens["radius"]["sm"], "radius-md": tokens["radius"]["md"],
        "radius-lg": tokens["radius"]["lg"], "radius-pill": tokens["radius"]["pill"],
        "shadow-card": tokens["shadow"]["card"], "shadow-hover": tokens["shadow"]["hover"],
        "font-ja": tokens["type"]["fontJa"], "font-latin": tokens["type"]["fontLatin"],
        "font-h1": tokens["type"]["h1"], "font-h2": tokens["type"]["h2"],
        "font-h3": tokens["type"]["h3"], "font-body": tokens["type"]["body"],
        "font-caption": tokens["type"]["caption"],
    }
    for key, value in mapping.items():
        if not isinstance(value, str) or any(char in value for char in ";{}<>"):
            raise ValueError(f"unsafe design token: {key}")
    lines = ["/* Generated from data/design-tokens.json; do not edit directly. */", ":root {"]
    lines += [f"  --cxs-{key}: {value};" for key, value in mapping.items()]
    return "\n".join(lines + ["}", ""])


def replace_marked(source: str, marker: str, content: str) -> str:
    start = f"<!-- BUILD:{marker} -->"
    end = f"<!-- /BUILD:{marker} -->"
    if source.count(start) != 1 or source.count(end) != 1:
        raise ValueError(f"expected exactly one {marker} marker pair")
    before, tail = source.split(start, 1)
    _, after = tail.split(end, 1)
    return before + start + "\n" + content + "\n" + end + after


def write_output(path: Path, content: str, check: bool) -> bool:
    current = path.read_text(encoding="utf-8") if path.exists() else None
    if current == content:
        return False
    if check:
        print(f"stale: {path.relative_to(ROOT)}")
    else:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        print(f"wrote: {path.relative_to(ROOT)}")
    return True


def build(check: bool = False) -> int:
    services = read_json(DATA / "services.json")
    groups = read_json(DATA / "service-groups.json")
    tokens = read_json(DATA / "design-tokens.json")
    validate(services, groups)
    index_path = ROOT / "index.html"
    index_source = index_path.read_text(encoding="utf-8")
    header, footer = extract_block(index_source, "header"), extract_block(index_source, "footer")
    outputs: dict[Path, str] = {}
    outputs[ROOT / "css" / "web-system-tokens.css"] = render_tokens(tokens)
    outputs[index_path] = replace_marked(index_source, "SERVICES", render_home(services, groups))
    list_schema = {"@context": "https://schema.org", "@type": "ItemList", "itemListElement": [
        {"@type": "ListItem", "position": i, "name": service["name"], "url": SITE + service["href"]}
        for i, service in enumerate(services, 1)
    ]}
    list_body = render_list(services, groups)
    outputs[SERVICES_DIR / "index.html"] = render_page(
        list_body, "サービス一覧｜Contents X", "Sales XとCreative Xのサービス一覧。新しい商談づくり、検索・AI対策、顧客管理、マンガ・アニメ・映像による価値訴求を支援します。",
        "/services/", [breadcrumbs_json([("ホーム", SITE + "/"), ("サービス", SITE + "/services/")]), list_schema], header, footer,
    )
    for service in services:
        path = service["href"]
        service_schema = {"@context": "https://schema.org", "@type": "Service", "name": service["name"],
                          "description": service["hoverSummary"], "url": SITE + path,
                          "provider": {"@type": "Organization", "@id": SITE + "/#organization"}}
        outputs[SERVICES_DIR / service["slug"] / "index.html"] = render_page(
            render_detail(service, services),
            f"{service['name']}｜Contents X", service.get("metaDescription", service["hoverSummary"]), path,
            [breadcrumbs_json([("ホーム", SITE + "/"), ("サービス", SITE + "/services/"), (service["name"], SITE + path)]), service_schema],
            header, footer,
        )
    sitemap_path = ROOT / "sitemap.xml"
    sitemap = sitemap_path.read_text(encoding="utf-8")
    urls = ["/services/"] + [service["href"] for service in services]
    entries = "\n".join(f"  <url><loc>{SITE}{path}</loc></url>" for path in urls)
    outputs[sitemap_path] = replace_marked(sitemap, "SERVICES", entries)
    changed = sum(write_output(path, content, check) for path, content in outputs.items())
    stale_files = [
        page for page in SERVICES_DIR.glob("*/index.html")
        if page.parent.name not in {service["slug"] for service in services}
        and SIGNATURE in page.read_text(encoding="utf-8")
    ]
    for page in stale_files:
        if check:
            print(f"stale generated page: {page.relative_to(ROOT)}")
        else:
            page.unlink()
            print(f"removed generated page: {page.relative_to(ROOT)}")
    changed += len(stale_files)
    print(f"services: {len(services)}, groups: {len(groups)}, changed: {changed}")
    return 1 if check and changed else 0


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail when generated files are out of date")
    args = parser.parse_args()
    try:
        sys.exit(build(check=args.check))
    except (ValueError, KeyError, json.JSONDecodeError) as error:
        print(f"build-services: {error}", file=sys.stderr)
        sys.exit(2)
