#!/usr/bin/env python3
"""Build the TOP service link and static service pages from data/services.json.

Usage: python3 tools/build-services.py [--check]
The same command runs in the Pages workflow, so a service addition needs data only.
"""

from __future__ import annotations

import argparse
import html
import json
import re
import sys
from pathlib import Path
from urllib.parse import urlsplit

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "data"
TEMPLATES = ROOT / "tools" / "templates"
SERVICES_DIR = ROOT / "services"
SITE = "https://contentsx.jp"
SIGNATURE = "<!-- Generated by tools/build-services.py; edit data/services.json -->"
SLUG = re.compile(r"^[a-z0-9-]+$")
IMAGE_PATH = re.compile(r"^/material/[A-Za-z0-9/_-]+\.(?:webp|avif|png|jpg)$")
PLACEHOLDER = re.compile(r"{{[A-Z_]+}}")


def esc(value: object) -> str:
    return html.escape(str(value), quote=True)


def read_json(path: Path):
    return json.loads(path.read_text(encoding="utf-8"))


def validate(services: list[dict], groups: list[dict]) -> None:
    if not isinstance(services, list) or not isinstance(groups, list):
        raise ValueError("services and groups must be arrays")
    required = {"id", "slug", "group", "name", "eyebrow", "shortCopy", "hoverSummary", "tags", "icon", "href", "destination", "featured"}
    group_ids: set[str] = set()
    for group in groups:
        if not isinstance(group, dict) or not all(group.get(key) for key in ("id", "name", "tagline", "summary")):
            raise ValueError(f"invalid group: {group!r}")
        if not SLUG.fullmatch(group["id"]) or group["id"] in group_ids:
            raise ValueError(f"invalid or duplicate group: {group['id']!r}")
        group_ids.add(group["id"])
    ids: set[str] = set()
    slugs: set[str] = set()
    for service in services:
        if not isinstance(service, dict) or not required.issubset(service):
            raise ValueError(f"service missing required fields: {service!r}")
        service_id, slug = service["id"], service["slug"]
        if not SLUG.fullmatch(service_id) or service_id in ids:
            raise ValueError(f"invalid or duplicate service id: {service_id!r}")
        if not SLUG.fullmatch(slug) or slug in slugs:
            raise ValueError(f"invalid or duplicate slug: {slug!r}")
        if service["group"] not in group_ids:
            raise ValueError(f"unknown group for {service_id}: {service['group']!r}")
        if service["href"] != f"/services/{slug}/":
            raise ValueError(f"href must match slug for {service_id}")
        destination = service["destination"]
        parsed = urlsplit(destination) if isinstance(destination, str) else None
        approved_host = parsed and parsed.scheme == "https" and (parsed.hostname == "contentsx.jp" or (parsed.hostname or "").endswith(".contentsx.jp"))
        if destination != f"/services/#{slug}" and not approved_host:
            raise ValueError(f"invalid destination for {service_id}: {destination!r}")
        if not (ROOT / "material" / "web-system" / "icons" / f"{service['icon']}.svg").is_file():
            raise ValueError(f"unknown icon for {service_id}: {service['icon']!r}")
        if not all(isinstance(service[key], str) and service[key].strip() for key in ("name", "eyebrow", "shortCopy", "hoverSummary")):
            raise ValueError(f"empty text field for {service_id}")
        if not isinstance(service["tags"], list) or not all(isinstance(tag, str) and tag for tag in service["tags"]):
            raise ValueError(f"invalid tags for {service_id}")
        if not isinstance(service["featured"], bool):
            raise ValueError(f"invalid featured for {service_id}")
        for field in ("features", "challenges", "steps", "useCases"):
            if field in service and (not isinstance(service[field], list) or not all(isinstance(item, str) and item for item in service[field])):
                raise ValueError(f"invalid {field} for {service_id}")
        for faq in service.get("faqs", []):
            if not isinstance(faq, dict) or not faq.get("question") or not faq.get("answer"):
                raise ValueError(f"invalid FAQ for {service_id}")
        for field in ("image", "hoverImage"):
            if field not in service:
                continue
            image = service[field]
            if not isinstance(image, str) or not IMAGE_PATH.fullmatch(image):
                raise ValueError(f"invalid {field} for {service_id}")
            image_path = (ROOT / image.lstrip("/")).resolve()
            if not image_path.is_relative_to(ROOT / "material") or not image_path.is_file():
                raise ValueError(f"missing or unsafe {field} for {service_id}")
        ids.add(service_id)
        slugs.add(slug)


def render_template(name: str, values: dict[str, str]) -> str:
    result = (TEMPLATES / name).read_text(encoding="utf-8")
    for key, value in values.items():
        result = result.replace("{{" + key + "}}", value)
    remaining = PLACEHOLDER.findall(result)
    if remaining:
        raise ValueError(f"unfilled template values: {remaining}")
    return result


def render_icon(name: str, class_name: str = "cxs-icon") -> str:
    source = (ROOT / "material" / "web-system" / "icons" / f"{name}.svg").read_text(encoding="utf-8").strip()
    return source.replace("<svg ", f'<svg class="{class_name}" aria-hidden="true" focusable="false" ', 1)


def render_tags(tags: list[str], class_name: str = "cxs-tags") -> str:
    if not tags:
        return ""
    return f'<ul class="{class_name}">' + "".join(f"<li>{esc(tag)}</li>" for tag in tags) + "</ul>"


def render_card(service: dict, context: str) -> str:
    control_id = f"cxs-{context}-{service['slug']}-more"
    name = esc(service["name"])
    href = esc(service_destination(service))
    coming_soon = service["id"] in COMING_SOON
    detail_button = "" if coming_soon else f'<a class="cxs-icon-button" href="{href}" aria-label="{name}の詳細を見る">{render_icon("arrow-right")}</a>'
    more_copy = "乞うご期待" if coming_soon else esc(service["hoverSummary"])
    more_link = "" if coming_soon else f'<a class="cxs-card__detail-link" href="{href}">詳しく見る <span aria-hidden="true">→</span></a>'
    photo = (f'<span class="cxs-card__photo" aria-hidden="true" style="background-image:url(\'{esc(service["hoverImage"])}\')"></span>'
             if service.get("hoverImage") else "")
    return re.sub(r"(?m)^[ \t]+$", "", f'''<article class="cxs-card{' cxs-card--coming-soon' if coming_soon else ''}" data-group="{esc(service['group'])}" data-featured="{str(service['featured']).lower()}"{' tabindex="0"' if coming_soon else ''}>
  <div class="cxs-card__intro">
    <div class="cxs-card__icon">{render_icon(service['icon'])}</div>
    <h3>{name}</h3>
    <p class="cxs-card__short">{esc(service['shortCopy'])}</p>
    <div class="cxs-card__actions">
      <button class="cxs-card__expand" type="button" aria-expanded="false" aria-controls="{control_id}">{'公開予定を見る' if coming_soon else '概要を見る'}</button>
      {detail_button}
    </div>
  </div>
  <div class="cxs-card__more" id="{control_id}">
    {photo}
    <button class="cxs-card__close" type="button" aria-label="{name}の概要を閉じる">閉じる ×</button>
    <h4>{name}</h4>
    <p>{more_copy}</p>
    {'' if coming_soon else render_tags(service['tags'], 'cxs-tags cxs-tags--on-accent')}
    {more_link}
  </div>
</article>''')


def render_group(group: dict, services: list[dict], context: str) -> str:
    members = [service for service in services if service["group"] == group["id"]]
    if not members:
        return ""
    group_id = esc(group["id"])
    heading_id = f"cxs-{context}-{group_id}-title"
    cards = "\n".join(render_card(service, context) for service in members)
    group_name = esc(group["name"])
    group_heading = (f'<a href="/services/{group_id}-x/">{group_name}</a>'
                     if context == "list" else group_name)
    return f'''<section class="cxs-section cxs-service-group" id="{context}-group-{group_id}" data-group="{group_id}" aria-labelledby="{heading_id}">
  <div class="cxs-container">
    <div class="cxs-section-header">
      <div><p class="cxs-eyebrow">{esc(group.get('eyebrow', group['name']))}</p><h2 id="{heading_id}">{group_heading}</h2><p class="cxs-section-header__tagline">{esc(group['tagline'])}</p></div>
      <p class="cxs-section-header__summary">{esc(group['summary'])}</p>
    </div>
    <div class="cxs-service-grid">{cards}</div>
  </div>
</section>'''


def render_home() -> str:
    # The full data-driven grid lives only on /services/. Keep a short path from TOP.
    return '''<section class="cxs-home-services" id="services" aria-labelledby="cxsHomeServicesTitle">
  <div class="cxs-container"><div class="cxs-home-services__intro">
    <div><p class="cxs-eyebrow">OUR SERVICES</p><h2 id="cxsHomeServicesTitle">売上につながる、サービス。</h2><p>Sales XとCreative Xのサービスを、専用ページでご紹介します。</p></div>
    <a class="cxs-text-link" href="/services/">サービス一覧を見る <span aria-hidden="true">→</span></a>
  </div></div>
</section>'''


def render_list(services: list[dict], groups: list[dict]) -> str:
    by_id = {group["id"]: group for group in groups}
    ordered = [by_id[group_id] for group_id in ("creative", "sales") if group_id in by_id]
    ordered += [group for group in groups if group["id"] not in {item["id"] for item in ordered}]
    sections = []
    for index, group in enumerate(ordered, 1):
        if index > 1:
            sections.append(f'<div class="cxsd-next"><span>NEXT FIELD</span><strong>続いて {esc(group["name"])} のサービス</strong></div>')
        sections.append(render_directory_group(group, services, index))
    return render_template("service-list.html.tpl", {"GROUPS": "\n".join(sections)})


DIRECTORY_IMAGES = {
    "creative": ("/material/service-2026/creative-hero-v2.webp", 1536, 1024),
    "sales": ("/material/service-2026/sales-hero-v2.webp", 1672, 941),
}


def service_destination(service: dict) -> str:
    return service["destination"]


def render_directory_card(service: dict, index: int) -> str:
    service_id = service["id"]
    name = esc(service["name"])
    image = GROUP_IMAGES.get(service_id, service.get("hoverImage") or service.get("image"))
    width, height = GROUP_IMAGE_SIZES.get(service_id, (0, 0))
    dimensions = f' width="{width}" height="{height}"' if width and height else ""
    coming_soon = service_id in COMING_SOON
    video = GROUP_VIDEOS.get(service_id)
    if video:
        video_src, caption_src, title = video
        visual = (f'<button class="cxg-video-play" type="button" data-video-src="{esc(video_src)}" '
                  f'data-caption-src="{esc(caption_src)}" aria-label="{esc(title)}を音声付きで再生">'
                  f'<img src="{esc(image)}" alt=""{dimensions} loading="lazy">'
                  '<span class="cxg-video-play__icon" aria-hidden="true">▶</span>'
                  '<span class="cxg-video-play__caption" aria-hidden="true">動画を再生</span></button>')
    else:
        photo = f'<img src="{esc(image)}" alt=""{dimensions} loading="lazy">'
        visual = photo if coming_soon else (
            f'<a class="cxsd-card__image-link" href="{esc(service_destination(service))}" '
            f'aria-label="{name}の公式サイトを見る">{photo}</a>'
        )
    if coming_soon:
        action = '<span class="cxsd-card__soon">公開予定</span>'
    elif service_id == "bizvideo":
        action = '<a href="/contact">制作について相談 <span aria-hidden="true">↗</span></a>'
    else:
        action = f'<a href="{esc(service_destination(service))}">公式サイトを見る <span aria-hidden="true">↗</span></a>'
    overlay = '乞うご期待' if coming_soon else esc(service["hoverSummary"])
    title = name if coming_soon or service_id == "bizvideo" else f'<a href="{esc(service_destination(service))}">{name}</a>'
    return f'''<article class="cxsd-card cxsd-card--{esc(service_id)}{' cxsd-card--soon' if coming_soon else ''}" id="{esc(service['slug'])}">
  <div class="cxsd-card__visual">{visual}<div class="cxsd-card__overlay" aria-hidden="true"><span>{overlay}</span></div></div>
  <div class="cxsd-card__body"><div class="cxsd-card__label"><span>{index:02}</span><span>{esc(service['eyebrow'])}</span></div><h3>{title}</h3>
    <p>{esc(service['shortCopy'])}</p><div class="cxsd-card__actions">{action}</div></div>
</article>'''


def render_directory_group(group: dict, services: list[dict], index: int) -> str:
    group_id = group["id"]
    image, width, height = DIRECTORY_IMAGES[group_id]
    members = [service for service in services if service["group"] == group_id]
    cards = "\n".join(render_directory_card(service, number) for number, service in enumerate(members, 1))
    name = esc(group["name"])
    heading = "h1" if index == 1 else "h2"
    image_loading = 'fetchpriority="high"' if index == 1 else 'loading="lazy"'
    return f'''<section class="cxsd-group cxsd-group--{esc(group_id)}" id="list-group-{esc(group_id)}" aria-labelledby="cxsd-{esc(group_id)}-title">
  <div class="cxsd-group__intro"><div class="cxsd-group__image"><img src="{image}" alt="" width="{width}" height="{height}" {image_loading} decoding="async"></div>
    <div class="cxsd-group__copy"><span class="cxsd-group__number">{index:02} / BUSINESS FIELD</span><p class="cxsd-group__eyebrow">{esc(group['eyebrow'])}</p>
      <{heading} id="cxsd-{esc(group_id)}-title">{name}</{heading}><strong>{esc(group['tagline'])}</strong><p>{esc(group['summary'])}</p>
      <a class="cxsd-group__link" href="/services/{esc(group_id)}-x/">{name} を詳しく見る <span aria-hidden="true">↗</span></a>
    </div></div>
  <div class="cxs-container cxsd-group__services"><div class="cxsd-group__services-head"><span>OUR SERVICES</span><h3>{name} のサービス</h3><p>気になるサービスから、公式サイトや制作事例をご覧ください。</p></div>
    <div class="cxsd-grid">{cards}</div></div>
</section>'''


def render_redirect(service: dict) -> str:
    destination = service_destination(service)
    safe_destination = esc(destination)
    script_destination = json.dumps(destination, ensure_ascii=False).replace("<", "\\u003c")
    return f'''<!DOCTYPE html>
{SIGNATURE}
<html lang="ja"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="robots" content="noindex,follow"><meta http-equiv="refresh" content="0;url={safe_destination}">
<link rel="canonical" href="{safe_destination}"><title>{esc(service['name'])}｜Contents X</title>
<script>location.replace({script_destination});</script></head><body><p><a href="{safe_destination}">{esc(service['name'])}の案内先へ進む</a></p></body></html>
'''


def render_list_items(items: list[str], class_name: str = "cxs-feature-list") -> str:
    return f'<ul class="{class_name}">' + "".join(f"<li>{esc(item)}</li>" for item in items) + "</ul>"


def render_detail_sections(service: dict, services: list[dict]) -> str:
    slug = service["slug"]
    tabs: list[tuple[str, str]] = [("overview", "概要")]
    overview = f'<p class="cxs-detail-lead">{esc(service["hoverSummary"])}</p>'
    if service.get("challenges"):
        overview += '<h3>こんな課題に</h3>' + render_list_items(service["challenges"])
    panels = [("overview", overview)]
    if service.get("features"):
        tabs.append(("features", "できること"))
        panels.append(("features", "<h3>サービスでできること</h3>" + render_list_items(service["features"])))
    related = [item for item in services if item["group"] == service["group"] and item["id"] != service["id"] and item["id"] not in COMING_SOON]
    if related:
        tabs.append(("related", "関連サービス"))
        links = "".join(f'<li><a href="{esc(service_destination(item))}">{esc(item["name"])} <span aria-hidden="true">→</span></a></li>' for item in related)
        panels.append(("related", f'<h3>同じカテゴリのサービス</h3><ul class="cxs-related-list">{links}</ul>'))
    buttons = "".join(
        f'<button type="button" role="tab" id="cxs-tab-{slug}-{key}" aria-controls="cxs-panel-{slug}-{key}" aria-selected="{str(index == 0).lower()}" tabindex="{0 if index == 0 else -1}">{label}</button>'
        for index, (key, label) in enumerate(tabs)
    )
    contents = "".join(
        f'<section class="cxs-tab-panel" role="tabpanel" id="cxs-panel-{slug}-{key}" aria-labelledby="cxs-tab-{slug}-{key}" tabindex="0">{body}</section>'
        for key, body in panels
    )
    result = f'''<section class="cxs-section cxs-detail-content" aria-label="{esc(service['name'])}の詳細">
  <div class="cxs-container"><h2 class="sr-only">{esc(service['name'])}の詳細</h2><div class="cxs-tabs" role="tablist" aria-label="サービス情報">{buttons}</div><div class="cxs-tab-panels">{contents}</div></div>
</section>'''
    for field, label in (("steps", "導入の流れ"), ("useCases", "活用シーン")):
        if service.get(field):
            result += f'<section class="cxs-section cxs-detail-extra"><div class="cxs-container"><h2>{label}</h2>{render_list_items(service[field])}</div></section>'
    if service.get("faqs"):
        faq_items = "".join(
            f'<details class="cxs-accordion"><summary>{esc(faq["question"])}</summary><p>{esc(faq["answer"])}</p></details>'
            for faq in service["faqs"]
        )
        result += f'<section class="cxs-section cxs-detail-extra"><div class="cxs-container"><h2>よくある質問</h2>{faq_items}</div></section>'
    return result


def render_detail(service: dict, services: list[dict]) -> str:
    visual = (render_landing_visual(service, GROUP_IMAGES[service["id"]], f' width="{GROUP_IMAGE_SIZES[service["id"]][0]}" height="{GROUP_IMAGE_SIZES[service["id"]][1]}"')
              if service["id"] in GROUP_VIDEOS else
              f'<img src="{esc(service["image"])}" alt="{esc(service["name"])}のサービスイメージ" loading="lazy">'
              if service.get("image") else
              f'<img src="{esc(service["hoverImage"])}" alt="" loading="lazy">'
              if service.get("hoverImage") else render_icon(service["icon"], "cxs-detail-hero__visual-icon"))
    values = {
        "GROUP_ID": esc(service["group"]),
        "NAME": esc(service["name"]),
        "EYEBROW": esc(service["eyebrow"]),
        "SHORT_COPY": esc(service["shortCopy"]),
        "SUMMARY": esc(service["hoverSummary"]),
        "TAGS": render_tags(service["tags"]),
        "ICON": render_icon(service["icon"]),
        "VISUAL_ICON": visual,
        "VISUAL_CLASS": f' cxs-detail-hero__visual--{esc(service["id"])}' if service["id"] in (*GROUP_VIDEOS, "bizmanga", "bizrecruit") else "",
        "DETAIL_SECTIONS": render_detail_sections(service, services),
    }
    return render_template("service-detail.html.tpl", values)


GROUP_IMAGES = {
    "bizform": "/material/service-2026/bizform-research-v2.webp",
    "bizrecruit": "/material/service-2026/bizrecruit-service.webp",
    "bizmanga": "/material/service-2026/manga-justice-cover.webp",
    "bizanime": "/material/service-2026/bizanime-ieye.jpg",
    "bizvideo": "/material/service-2026/bizvideo-memory-town.jpg",
}
GROUP_IMAGE_SIZES = {
    "bizform": (1672, 941), "bizaio": (1672, 941),
    "bizkarte": (1672, 941), "bizrecruit": (1672, 941),
    "bizmanga": (1407, 2000), "bizanime": (1280, 720), "bizvideo": (1280, 720),
}
COMING_SOON = {"bizaio", "bizkarte"}
GROUP_VIDEOS = {
    "bizanime": ("/material/service-2026/bizanime-ieye.mp4", "/material/service-2026/bizanime-ieye.ja.vtt", "ビズアニメ制作事例「I eye」"),
    "bizvideo": ("/material/service-2026/bizvideo-memory-town.mp4", "/material/service-2026/bizvideo-memory-town.ja.vtt", "ビズビデオ制作事例「私を置いて、記憶だけ残った街」"),
}


def render_landing_visual(service: dict, image: str | None, dimensions: str) -> str:
    video = GROUP_VIDEOS.get(service["id"])
    if video:
        video_src, caption_src, title = video
        return (f'<button class="cxg-video-play" type="button" data-video-src="{video_src}" data-caption-src="{caption_src}" '
                f'aria-label="{esc(title)}を音声付きで再生">'
                f'<img src="{esc(image)}" alt=""{dimensions} loading="lazy">'
                '<span class="cxg-video-play__icon" aria-hidden="true">▶</span>'
                '<span class="cxg-video-play__caption" aria-hidden="true">動画を再生</span></button>')
    return (f'<img src="{esc(image)}" alt=""{dimensions} loading="lazy">'
            if image else render_icon(service["icon"], "cxg-service-card__icon"))


def render_coming_soon() -> str:
    return '<div class="cxg-coming-soon"><strong>乞うご期待</strong><span>サービスのご案内を準備中です</span></div>'


def render_landing_card(service: dict, index: int) -> str:
    service_id = service["id"]
    image = GROUP_IMAGES.get(service_id, service.get("hoverImage") or service.get("image"))
    href = service_destination(service)
    # Decorative card imagery comes from approved site assets, never the AI mockup screenshots.
    size = GROUP_IMAGE_SIZES.get(service_id)
    dimensions = f' width="{size[0]}" height="{size[1]}"' if size else ""
    image_markup = render_landing_visual(service, image, dimensions)
    visual_class = "" if image else " cxg-service-card__image--icon"
    coming_soon = service_id in COMING_SOON
    action = (f'<button class="cxg-coming-soon__trigger" type="button" aria-label="{esc(service["name"])}は準備中です">公開予定 <span aria-hidden="true">→</span></button>'
              if coming_soon else '<a href="/contact">制作について相談 <span aria-hidden="true">→</span></a>'
              if service_id == "bizvideo" else f'<a href="{esc(href)}">公式サイトを見る <span aria-hidden="true">↗</span></a>')
    return re.sub(r"(?m)^[ \t]+$", "", f'''<article class="cxg-service-card cxg-service-card--{service_id}{' cxg-service-card--coming-soon' if coming_soon else ''}">
  <div class="cxg-service-card__image{visual_class}">{image_markup}</div>
  <div class="cxg-service-card__body"><small>{index:02}</small><h3>{esc(service['name'])}</h3>
    <p>{esc(service['hoverSummary'])}</p>{action}</div>
  {render_coming_soon() if coming_soon else ''}
</article>''')


def render_landing_row(service: dict, index: int) -> str:
    image = GROUP_IMAGES.get(service["id"], service.get("hoverImage") or service.get("image"))
    size = GROUP_IMAGE_SIZES.get(service["id"])
    dimensions = f' width="{size[0]}" height="{size[1]}"' if size else ""
    visual = (f'<img src="{esc(image)}" alt=""{dimensions} loading="lazy">' if image else
              render_icon(service["icon"], "cxg-service-card__icon"))
    coming_soon = service["id"] in COMING_SOON
    action = (f'<button class="cxg-coming-soon__trigger" type="button" aria-label="{esc(service["name"])}は準備中です">公開予定 →</button>'
              if coming_soon else f'<a href="{esc(service_destination(service))}">公式サイトを見る ↗</a>')
    return re.sub(r"(?m)^[ \t]+$", "", f'''<article class="cxg-detail-row{' cxg-detail-row--coming-soon' if coming_soon else ''}">
  <div class="cxg-detail-row__visual{' cxg-detail-row__visual--icon' if not image else ''}">{visual}
    {render_coming_soon() if coming_soon else f'<div class="cxg-detail-row__hover"><strong>{esc(service["name"])}</strong><span>{esc(service["hoverSummary"])}</span></div>'}</div>
  <div class="cxg-detail-row__copy"><span>{index:02} / {esc(service['name'])}</span><h3>{esc(service['shortCopy'])}</h3>
    <p>{esc(service['hoverSummary'])}</p>{action}</div>
</article>''')


def render_creative_mini(service: dict) -> str:
    href = service_destination(service)
    image = GROUP_IMAGES.get(service["id"], service.get("hoverImage") or service.get("image"))
    size = GROUP_IMAGE_SIZES.get(service["id"])
    dimensions = f' width="{size[0]}" height="{size[1]}"' if size else ""
    visual = (f'<img src="{esc(image)}" alt=""{dimensions} loading="lazy">' if image else
              render_icon(service["icon"], "cxg-service-card__icon"))
    return f'<a href="{esc(href)}">{visual}<span>{esc(service["name"])}</span></a>'


def render_group_landing(group_id: str, services: list[dict]) -> str:
    sales = [item for item in services if item["group"] == "sales"]
    creative = [item for item in services if item["group"] == "creative"]
    if group_id == "sales":
        return render_template("service-group-sales.html.tpl", {
            "SALES_CARDS": "\n".join(render_landing_card(item, i) for i, item in enumerate(sales, 1)),
            "SALES_ROWS": "\n".join(render_landing_row(item, i) for i, item in enumerate(sales, 1)),
            "CREATIVE_MINI_CARDS": "\n".join(render_creative_mini(item) for item in creative),
        })
    return render_template("service-group-creative.html.tpl", {
        "CREATIVE_CARDS": "\n".join(render_landing_card(item, i) for i, item in enumerate(creative, 1)),
    })


def script_json(data: dict) -> str:
    payload = json.dumps(data, ensure_ascii=False, separators=(",", ":")).replace("<", "\\u003c")
    return f'<script type="application/ld+json">{payload}</script>'


def breadcrumbs_json(items: list[tuple[str, str]]) -> dict:
    return {"@context": "https://schema.org", "@type": "BreadcrumbList", "itemListElement": [
        {"@type": "ListItem", "position": index, "name": name, "item": url}
        for index, (name, url) in enumerate(items, 1)
    ]}


def extract_block(source: str, tag: str) -> str:
    opening = re.search(rf"<{tag}\b[^>]*>", source)
    if not opening:
        raise ValueError(f"missing <{tag}> in service chrome source")
    closing = source.find(f"</{tag}>", opening.end())
    if closing < 0:
        raise ValueError(f"missing </{tag}> in service chrome source")
    return source[opening.start(): closing + len(tag) + 3]


def render_page(body: str, title: str, description: str, path: str, json_ld: list[dict], header: str, footer: str, cta_mount: bool = True) -> str:
    canonical = f"{SITE}{path}"
    page = render_template("service-page.html.tpl", {
        "TITLE": esc(title), "DESCRIPTION": esc(description), "CANONICAL": esc(canonical),
        "JSON_LD": "\n  ".join(script_json(item) for item in json_ld),
        "HEADER": header, "FOOTER": footer, "BODY": body,
    })
    if not cta_mount:
        page = page.replace('  <section id="cxCtaMount" data-cx-page-cta></section>\n', '')
    return page.replace("<!DOCTYPE html>", f"<!DOCTYPE html>\n{SIGNATURE}", 1)


def render_tokens(tokens: dict) -> str:
    mapping = {
        "ink": tokens["colors"]["ink"], "text": tokens["colors"]["text"],
        "muted": tokens["colors"]["muted"], "border": tokens["colors"]["border"],
        "background": tokens["colors"]["background"], "surface": tokens["colors"]["surface"],
        "sales": tokens["colors"]["sales"], "sales-soft": tokens["colors"]["salesSoft"],
        "creative": tokens["colors"]["creative"], "creative-soft": tokens["colors"]["creativeSoft"],
        "container-max": tokens["layout"]["containerMax"],
        "gutter-desktop": tokens["layout"]["pageGutterDesktop"],
        "gutter-mobile": tokens["layout"]["pageGutterMobile"],
        "section-desktop": tokens["layout"]["sectionSpaceDesktop"],
        "section-mobile": tokens["layout"]["sectionSpaceMobile"],
        "radius-sm": tokens["radius"]["sm"], "radius-md": tokens["radius"]["md"],
        "radius-lg": tokens["radius"]["lg"], "radius-pill": tokens["radius"]["pill"],
        "shadow-card": tokens["shadow"]["card"], "shadow-hover": tokens["shadow"]["hover"],
        "font-ja": tokens["type"]["fontJa"], "font-latin": tokens["type"]["fontLatin"],
        "font-h1": tokens["type"]["h1"], "font-h2": tokens["type"]["h2"],
        "font-h3": tokens["type"]["h3"], "font-body": tokens["type"]["body"],
        "font-caption": tokens["type"]["caption"],
    }
    for key, value in mapping.items():
        if not isinstance(value, str) or any(char in value for char in ";{}<>"):
            raise ValueError(f"unsafe design token: {key}")
    # Colours and fonts alias the site-wide brand tokens (css/brand-system-2026.css), so the service
    # pages and every other page share one source. The JSON value stays as the fallback.
    brand = {"ink": "color-ink", "text": "color-body", "muted": "color-muted", "border": "color-border",
             "background": "color-white", "surface": "color-surface", "sales": "color-sales",
             "sales-soft": "color-sales-soft", "creative": "color-creative", "creative-soft": "color-creative-soft",
             "font-ja": "font-ja", "font-latin": "font-latin"}
    lines = ["/* Generated from data/design-tokens.json; do not edit directly. */", ":root {"]
    lines += [f"  --cxs-{key}: var(--cx-{brand[key]}, {value});" if key in brand else f"  --cxs-{key}: {value};"
              for key, value in mapping.items()]
    return "\n".join(lines + ["}", ""])


def replace_marked(source: str, marker: str, content: str) -> str:
    start = f"<!-- BUILD:{marker} -->"
    end = f"<!-- /BUILD:{marker} -->"
    if source.count(start) != 1 or source.count(end) != 1:
        raise ValueError(f"expected exactly one {marker} marker pair")
    before, tail = source.split(start, 1)
    _, after = tail.split(end, 1)
    return before + start + "\n" + content + "\n" + end + after


def write_output(path: Path, content: str, check: bool) -> bool:
    current = path.read_text(encoding="utf-8") if path.exists() else None
    if current == content:
        return False
    if check:
        print(f"stale: {path.relative_to(ROOT)}")
    else:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        print(f"wrote: {path.relative_to(ROOT)}")
    return True


def build(check: bool = False) -> int:
    services = read_json(DATA / "services.json")
    groups = read_json(DATA / "service-groups.json")
    tokens = read_json(DATA / "design-tokens.json")
    validate(services, groups)
    index_path = ROOT / "index.html"
    index_source = index_path.read_text(encoding="utf-8")
    # The renewed homepage intentionally has no header. Use the service index
    # as the source of the shared header and footer for generated service pages.
    chrome_source = (SERVICES_DIR / "index.html").read_text(encoding="utf-8")
    header = extract_block(chrome_source, "header")
    footer = extract_block(chrome_source, "footer")
    outputs: dict[Path, str] = {}
    outputs[ROOT / "css" / "web-system-tokens.css"] = render_tokens(tokens)
    if "<!-- BUILD:SERVICES -->" in index_source or "<!-- /BUILD:SERVICES -->" in index_source:
        outputs[index_path] = replace_marked(index_source, "SERVICES", render_home())
    list_schema = {"@context": "https://schema.org", "@type": "ItemList", "itemListElement": [
        {"@type": "ListItem", "position": i, "name": service["name"], "url":
         service_destination(service) if service_destination(service).startswith("https://") else SITE + service_destination(service)}
        for i, service in enumerate(services, 1)
    ]}
    list_body = render_list(services, groups)
    outputs[SERVICES_DIR / "index.html"] = render_page(
        list_body, "サービス一覧｜Contents X", "Creative XとSales Xのサービス一覧。マンガ・アニメ・映像による価値訴求と、新しい商談づくり、検索・AI対策、顧客管理を支援します。",
        "/services/", [breadcrumbs_json([("ホーム", SITE + "/"), ("サービス", SITE + "/services/")]), list_schema], header, footer,
    )
    for group in groups:
        group_path = f"/services/{group['id']}-x/"
        outputs[SERVICES_DIR / f"{group['id']}-x" / "index.html"] = render_page(
            render_group_landing(group["id"], services),
            f"{group['name']}｜Contents X", f"{group['name']}。{group['summary']}", group_path,
            [breadcrumbs_json([("ホーム", SITE + "/"), ("サービス", SITE + "/services/"), (group["name"], SITE + group_path)])],
            header, footer, cta_mount=False,
        )
    for service in services:
        # Preserve published URLs as tiny redirects; individual detail pages are retired.
        outputs[SERVICES_DIR / service["slug"] / "index.html"] = render_redirect(service)
    sitemap_path = ROOT / "sitemap.xml"
    sitemap = sitemap_path.read_text(encoding="utf-8")
    urls = ["/services/"] + [f"/services/{group['id']}-x/" for group in groups]
    entries = "\n".join(f"  <url><loc>{SITE}{path}</loc></url>" for path in urls)
    outputs[sitemap_path] = replace_marked(sitemap, "SERVICES", entries)
    changed = sum(write_output(path, content, check) for path, content in outputs.items())
    stale_files = [
        page for page in SERVICES_DIR.glob("*/index.html")
        if page.parent.name not in ({service["slug"] for service in services} | {f"{group['id']}-x" for group in groups})
        and SIGNATURE in page.read_text(encoding="utf-8")
    ]
    for page in stale_files:
        if check:
            print(f"stale generated page: {page.relative_to(ROOT)}")
        else:
            page.unlink()
            print(f"removed generated page: {page.relative_to(ROOT)}")
    changed += len(stale_files)
    print(f"services: {len(services)}, groups: {len(groups)}, changed: {changed}")
    return 1 if check and changed else 0


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail when generated files are out of date")
    args = parser.parse_args()
    try:
        sys.exit(build(check=args.check))
    except (ValueError, KeyError, json.JSONDecodeError) as error:
        print(f"build-services: {error}", file=sys.stderr)
        sys.exit(2)
